server:
   port: 9000

spring:
  application:
    name: hook
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hook
    password: SethSqlPass21
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
    
logging:
  level:
    org:
      springframework: 
        web: INFO
        data: INFO